//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetServiceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureVIEW
    {
        public int procedureID { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
    }
}
